query GetCustomPostType(
  $pageId: ID!                 # supply a URI, slug, or numeric ID
  $idType: PageIdType = URI 
) {
  page(id: $pageId, idType: $idType) {
    id
    title                      # page title 
    heroSection {
      title
      subtitle
      button {
        url
        title
        target
      }
      featuredImage {
        node {
          sourceUrl
          altText
        }
      }
    }
    faqSection {
      faqs {
        nodes {
          id
          ... on Faq {
            title
            content
          }
        }
      }
    }
  }
}
