query GetHomePage {
  pageBy(uri: "/") {          
    id
    heroSection {
      title           
      subtitle       
      button {          
        url
        title
        target
      }
      featuredImage {       
        node {                  
            sourceUrl
            altText
        }
      }
    }
    featuredSteps {
      sectionTitle
      steps {
        title
        subtitle
        icon {
          node {
            sourceUrl
            altText
          }
        }
      }
    }
  }
  # Options page where all devices are included
  deviceView {
      deviceViewSettings {
        title
        subtitle
        searchFieldPlaceholder
        quickLinks {
          link {
            url
            title
            target
          }
        }
        selectDevices {
          deviceName {
            url
            title
            target
          }
          icon {
            node {
              sourceUrl
              altText
            }
          }
        }
      }
    }

  posts(first: 3) {           # latest 3 blog posts teaser
    nodes {
      id
      title
      uri
      featuredImage { node { sourceUrl altText } }
      excerpt
    }
  }
}