# query GetLaptopSlugs {
#   laptops(first: 100) {
#     nodes { uri }
#   }
# }

# query GetLaptopUris {
#   laptops(first: 100) {
#     nodes {
#       id
#       title
#       uri     # ← full slug / path
#     }
#   }
# }

