# query LaptopBySlug($uri: String!) {
#   postBy(uri: $uri) {
#     id
#     title
#   }
# }


# query NodeByUri($path: String!) {
#   nodeByUri(uri: $path) {
#     __typename
#     ... on Post {
#       id
#       title
#       uri
#     }
#   }
# }

# query LaptopBySlug($slug: ID!) {
#   post(id: $slug, idType: SLUG) {
#     id
#     title
#     uri   # /news/hello-world/
#   }
# }