
import type { Metadata } from "next";
import { Roboto, Ubuntu } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],      
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-roboto',
});

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  display: 'swap',              
  variable: '--font-ubuntu',
});

export const metadata: Metadata = {
  title: "Sell Used or Broken Laptops Online for Cash! - CashALaptop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${ubuntu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
